### PR TITLE
Add non-code VERSION file to package distribution

### LINKED ISSUE #4: Installing with Poetry does not install VERSION file
`>> poetry add lazy_alchemy`

> FileNotFoundError: [Errno 2] No such file or directory: '/home/anon/company/reps/project1/.venv/lib/python3.10/site-packages/lazy_alchemy/VERSION'

Inspecting the lazy_alchemy dir confirms the VERSION file is not present.

### PR DESCRIPTION
**Pull request by jonbiemond**
Update MANIFEST.in
- Fix file path in MANIFEST.in

Update setup.py
- Add include_package_data parameter  to setup()
- Specify sqlalchemy dependency version prior to 2.0

Bump with patch version to 0.0.3
Fixes #4

### CODE REVIEW

**Comment by jonbiemond** [comment]
This resolves the bug discussed in issue #4. Tested by uploading to test.pypi.org. Was able to replicate using both Pipenv and Poetry, and confirmed working using Pip, Pipenv and Poetry.

Also added sqlalchemy version constraint in setup.py. The package doesn't currently work with sqlalchemy 2.0.

**Comment by satyamsoni2211** [comment]
@jonbiemond Can you also remove support for python 3.6 from `tox`. I think the workflows are failing as it is not able to set up 3.6 versions. Also, I suppose minimum version that people have migrated to is 3.7.

**Comment by satyamsoni2211** [comment]
Also, Can you please remove `3.6` version for github workflows checkout. :) This would also require modifying minimum Python requirement to `>=3.7` in `setup.py` or `manifest.in` file.

**Comment by jonbiemond** [comment]
This workflow error is documented thoroughly here: actions/setup-python#544
Instead of removing support for `3.6`, may I suggest a separate PR for updating the workflow to use a less recent version of ubuntu for `3.6`, then rebase this branch and resubmit.

**Comment by jonbiemond** [comment]
Depends on #6 to be merged. Once #6 is merged, I will rebase and resubmit.

**Comment by satyamsoni2211** [comment]
@jonbiemond I have merged #6 . Can you rebase and then resubmit ?

**Comment by jonbiemond** [comment]
@satyamsoni2211 Thank you! I rebased, ready for review.

**Review by satyamsoni2211 — APPROVED** [review]
Looks Good

**Comment by satyamsoni2211** [comment]
@jonbiemond Thanks for your contribution. I have bumped  version of the library to `1.0.3` as it has 3 patches worked on. I did release a stable version of the API so it already has `1.0.0` released in [July](https://pypi.org/project/lazy-alchemy/1.0.0/). Here is the [latest release](https://pypi.org/project/lazy-alchemy/1.0.3/).

**Comment by satyamsoni2211** [comment]
Able to install it using poetry now :) 

```bash
(pdemo-py3.11) ~/pdemo poetry add lazy-alchemy
Using version ^1.0.3 for lazy-alchemy

Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/63/4b/f25378dfaddd294b7d0b893b833ed824dedcd31f6e99f480e449d984613b/SQLAlchemy-1.4.Resolving dependencies... (0.8s)

Writing lock file

Package operations: 2 installs, 0 updates, 0 removals

  • Installing sqlalchemy (1.4.48)
  • Installing lazy-alchemy (1.0.3)
```

```toml
[tool.poetry.dependencies]
python = "^3.11"
lazy-alchemy = "^1.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by satyamsoni2211** [comment]
Also, the version was `0.0.2` in `VERSION` file but `1.0.0` on PYPI cuz I would have updated it locally and pushed but would have forgot to commit 🙃. Anyways, everything is in sync now. Thanks for the update and your contribution 👍 . My Future plans are to migrate this to `SQLAlchemy 2.0`. Would be glad if you can help.

**Comment by jonbiemond** [comment]
@satyamsoni2211 Not at all! It was my pleasure. I would be interested in helping you migrate to `SQLAlchemy 2.0` in the future

**Pull request merged**
